version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - errname
    - errorlint
    - copyloopvar
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/shivase/gcauto
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    confidence: 0.8
  misspell:
    locale: US
  lll:
    line-length: 120
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  gocyclo:
    min-complexity: 15
  godot:
    scope: all
    capital: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - dupl
        - gosec
        - goconst
    - linters:
        - lll
      source: "^//go:generate "

formatters:
  enable:
    - gofmt
    - goimports